<?php

/* Header_2_1_0 */
'id_header_2_1_0' => array(
    'key' => 'id_header_2_1_0',
    'name' => 'header_2_1_0',
    'label' => 'Header 2.1.0',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'id_header_2_1_0_sub1',
            'label' => 'Menu',
            'name' => 'id_header_2_1_0_sub1',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                'id_header_2_1_0_sub1_layout1' => array(
                    'key' => 'id_header_2_1_0_sub1_layout1',
                    'name' => 'menu_don',
                    'label' => 'Menu đơn',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'id_header_2_1_0_sub1_layout1_sub',
                            'label' => 'Tên Menu',
                            'name' => 'title',
                            'type' => 'textarea',
                            'instructions' => 'Tên Menu | Link ',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 3,
                            'new_lines' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'id_header_2_1_0_sub1_layout2' => array(
                    'key' => 'id_header_2_1_0_sub1_layout2',
                    'name' => 'menu_sub',
                    'label' => 'Menu sub',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'id_header_2_1_0_sub1_layout2_sub1',
                            'label' => 'Menu Cha',
                            'name' => 'title',
                            'type' => 'textarea',
                            'instructions' => 'Tên Menu <br> Link ',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 3,
                            'new_lines' => '',
                        ),
                        array(
                            'key' => 'id_header_2_1_0_sub1_layout2_sub2',
                            'label' => 'Sub Menu',
                            'name' => 'col1',
                            'type' => 'wysiwyg',
                            'instructions' => 'Sử dụng groups UL>LI + Enter để tạo cột',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'id_header_2_1_0_sub1_layout3' => array(
                    'key' => 'id_header_2_1_0_sub1_layout3',
                    'name' => 'menu_sub_full',
                    'label' => 'Menu sub full',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'id_header_2_1_0_sub1_layout3_sub1',
                            'label' => 'Menu cha',
                            'name' => 'title',
                            'type' => 'textarea',
                            'instructions' => 'Tên Menu <br> Link <br> Số cột',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 3,
                            'new_lines' => '',
                        ),
                        array(
                            'key' => 'id_header_2_1_0_sub1_layout3_sub2',
                            'label' => 'Sub Menu',
                            'name' => 'col1',
                            'type' => 'wysiwyg',
                            'instructions' => 'Sử dụng groups UL>LI + Enter để tạo cột',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
            'button_label' => 'Thêm Menu',
            'min' => '',
            'max' => '',
        ),
    ),
    'min' => '',
    'max' => '',
),
/* End Header_2_1_0 */

?>