<?php

/*INFO 7.0.0*/
'id_info_7_0_0' => array(
    'key' => 'id_info_7_0_0',
    'name' => 'info_7_0_0',
    'label' => 'Info 7.0.0',
    'display' => 'block',
    'sub_fields' => array(
        /*Bắt đầu field*/
        array(
            /* Tab tiêu đề*/
            'key' => 'id_info_7_0_0_tab1',
            'label' => 'Thông Tin Chung',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'id_info_7_0_0_tab1_sub1',
            'label' => 'Tiêu đề',
            'name' => 'title1',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'hide_admin' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'id_info_7_0_0_tab1_sub2',
            'label' => 'Thông tin',
            'name' => 'info1_place',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'hide_admin' => 0,
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'id_info_7_0_0_tab1_sub2_layout1',
                    'label' => 'Thông tin chi tiết',
                    'name' => 'detail1_place',
                    'type' => 'textarea',
                    'instructions' => '
                        Dòng 1 : Tên dịch vụ <br>
                        Dòng 2 : Link ảnh ( Size 226x136 ) <br>
                        Dòng 3 : Link xem chi tiết
                    ',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => 3,
                    'new_lines' => '',
                ),
            ),
        ),
        array(
            /* Tab tiêu đề*/
            'key' => 'id_info_7_0_0_tab2',
            'label' => 'Công Nghệ',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'id_info_7_0_0_tab2_sub1',
            'label' => 'Tiêu đề',
            'name' => 'title2',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'hide_admin' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'id_info_7_0_0_tab2_sub2',
            'label' => 'Thông tin',
            'name' => 'info2_place',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'hide_admin' => 0,
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'id_info_7_0_0_tab2_sub2_layout1',
                    'label' => 'Tiêu đề',
                    'name' => 'detail2_place',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'hide_admin' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'id_info_7_0_0_tab2_sub2_layout2',
                    'label' => 'Link Url',
                    'name' => 'url_place',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'hide_admin' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),

        /*End field*/
    ),
    'min' => '',
    'max' => '',
),
/*END INFO 7.0.0*/

?>