<?php

/*NEWS 3.3.1*/
'id_news_3_3_1' => array(
    'key' => 'id_news_3_3_1',
    'name' => 'news_3_3_1',
    'label' => 'News 3.3.1',
    'display' => 'block',
    'sub_fields' => array(
        /*Bắt đầu field*/
        array(
            'key' => 'id_news_3_3_1_tab1',
            'label' => 'Tin Tức',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'id_news_3_3_1_tab1_sub1',
            'label' => 'Tiêu đề',
            'name' => 'title1',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'id_news_3_3_1_tab1_sub2',
            'label' => 'Danh sách tin',
            'name' => 'content1',
            'type' => 'relationship',
            'instructions' => 'Chọn 4 bài viết',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => '',
            'taxonomy' => '',
            'filters' => array(
                0 => 'search',
                1 => 'post_type',
                2 => 'taxonomy',
            ),
            'elements' => array(
                0 => 'featured_image',
            ),
            'min' => '',
            'max' => 4,
            'return_format' => 'id',
        ),
        array(
            'key' => 'id_news_3_3_1_tab2',
            'label' => 'Hoạt Động',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'id_news_3_3_1_tab2_sub1',
            'label' => 'Tiêu đề',
            'name' => 'title2',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'id_news_3_3_1_tab2_sub2',
            'label' => 'Danh sách tin',
            'name' => 'content2',
            'type' => 'relationship',
            'instructions' => 'Chọn 3 bài viết',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => '',
            'taxonomy' => '',
            'filters' => array(
                0 => 'search',
                1 => 'post_type',
                2 => 'taxonomy',
            ),
            'elements' => array(
                0 => 'featured_image',
            ),
            'min' => '',
            'max' => 3,
            'return_format' => 'id',
        ),
        array(
            'key' => 'id_news_3_3_1_tab3',
            'label' => 'Tư Vấn',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'id_news_3_3_1_tab3_sub1',
            'label' => 'Tiêu đề',
            'name' => 'title3',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'id_news_3_3_1_tab3_sub2',
            'label' => 'Danh sách tin',
            'name' => 'content3',
            'type' => 'relationship',
            'instructions' => 'Chọn 4 bài viết',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => '',
            'taxonomy' => '',
            'filters' => array(
                0 => 'search',
                1 => 'post_type',
                2 => 'taxonomy',
            ),
            'elements' => array(
                0 => 'featured_image',
            ),
            'min' => '',
            'max' => 4,
            'return_format' => 'id',
        ),

        /*End field*/
    ),
    'min' => '',
    'max' => '',
),
/*END NEWS 3.3.1*/

?>